# Generated by Django 2.2.16 on 2022-08-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220804_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descriprion',
            new_name='description',
        ),
    ]
